//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeavePortal.Adapters.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRequest
    {
        public int LeaveRequestId { get; set; }
        public int EmployeeId { get; set; }
        public decimal LeaveRequestedInDays { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public decimal RemainingLeaveBalance { get; set; }
        public bool LeaveCancelled { get; set; }
        public bool IsPending { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public System.DateTime DateRequested { get; set; }
    
        public virtual LeaveType LeaveType { get; set; }
    }
}
